on:
  push:
    branches:
      - main
      - prod

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        base: ${{ github.ref }}
        title: "Automated PR for ${{ github.ref_name }}"
        body: "This PR was created automatically by GitHub Actions."
        draft: false
